config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  get 'tos', to: 'welcome#tos', as: 'tos'
  get 'privacy_policy', to: 'welcome#privacy_policy', as: 'privacy_policy'

  authenticated :user do
    root 'hassles#index', as: 'user_authenticated_root'
  end
  root 'welcome#index'

  devise_for :users

  resources :hassles do
    collection do
      resources :achievement, only: %i[index], controller: 'hassles/achievement'
    end
  end

  namespace :api, format: 'json' do
    resources :hassles do
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hassle.rb
# frozen_string_literal: true

class Hassle < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :difficulty_levels, presence: true
  validates :frequency, presence: true
  validates :cost, presence: true

  scope :within_3_months, -> { where(created_at: 3.months.ago..Time.current) }
  scope :this_week, -> { where(created_at: Time.current.all_week) }
  scope :solved_on_this_week, -> { where(solved_on: Time.current.all_week) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :hassles, dependent: :destroy

  def fetch_registration_numbers
    hassles.where(is_made_by_admin: false).this_week.count
  end

  def fetch_registration_points
    hassles.this_week.sum(:registration_points)
  end

  def fetch_solution_numbers
    hassles.solved_on_this_week.count
  end

  def fetch_solution_points
    hassles.solved_on_this_week.sum(:total_points)
  end

  def fetch_all_hassles_numbers
    fetch_registration_numbers + fetch_solution_numbers
  end

  def fetch_all_hassles_points
    fetch_registration_points + fetch_solution_points
  end

  def show_chart
    [
      {
        name: '解決した!',
        data: hassles.within_3_months.group_by_week(:solved_on).sum(:total_points)
      },
      {
        name: '登録した!',
        data: hassles.within_3_months.group_by_week(:created_at).sum(:registration_points)
      }
    ]
  end
end

app/controllers/api/hassles_controller.rb
# frozen_string_literal: true

module Api
  class HasslesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_hassle, only: %i[show edit update destroy]
    skip_before_action :verify_authenticity_token

    rescue_from ActiveRecord::RecordNotFound do |_exception|
      render json: { error: '404 not found' }, status: :not_found
    end

    def index
      @hassles = current_user.hassles.order(total_points: :desc)
      render json: @hassles
    end

    def show
      render json: @hassle
    end

    def new
      @hassle = Hassle.new
    end

    def create
      @hassle = current_user.hassles.create(hassle_params)

      if @hassle.save
        render json: @hassle, status: :created
      else
        render json: @hassle.errors, status: :unprocessable_entity
      end
    end

    def edit
      @hassle
    end

    def update
      if @hassle.update(hassle_params)
        render json: { status: 'SUCCESS', data: @hassle }
      else
        render json: { status: 'ERROR', data: @hassle.errors }
      end
    end

    def destroy
      @hassle.destroy
    end

    private

    def hassle_params
      params.require(:hassle).permit(:title, :difficulty_levels, :frequency, :cost,
                                     :total_points, :solved, :solved_on, :is_made_by_admin, :registration_points)
    end

    def set_hassle
      @hassle = current_user.hassles.find(params[:id])
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    added_attrs = %i[email name password]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
    devise_parameter_sanitizer.permit :sign_in, keys: added_attrs
  end
end

app/controllers/hassles/achievement_controller.rb
# frozen_string_literal: true

module Hassles
  class AchievementController < ApplicationController
    before_action :authenticate_user!

    def index; end
  end
end

app/controllers/hassles_controller.rb
# frozen_string_literal: true

class HasslesController < ApplicationController
  before_action :authenticate_user!

  def show
    @hassle = current_user.hassles.find(params[:id])
  end

  private

  def hassle_params
    params.require(:hassle).permit(:title, :difficulty_levels, :frequency, :cost,
                                   :total_points, :solved, :solved_on)
  end
end

app/controllers/hassless_controller.rb
# frozen_string_literal: true

class HasslesController < ApplicationController
  before_action :authenticate_user!

  def show
    @hassle = current_user.hassles.find(params[:id])
  end

  private

  def hassle_params
    params.require(:hassle).permit(:title, :difficulty_levels, :frequency, :cost,
                                     :total_points, :solved, :solved_on)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
  def tos; end
  def privacy_policy; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'Chiikoma'
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/meta_tags_helper.rb
# frozen_string_literal: true

module MetaTagsHelper
  def default_meta_tags  # rubocop:disable Metrics/MethodLength
    {
      site: 'Chiikoma',
      reverse: true,
      separator: '|',
      description: '「小さな困りごと」気にしてあげませんか？',
      canonical: 'https://chiikoma.herokuapp.com/',
      noindex: !Rails.env.production?,
      icon: [
        { href: image_url('favicon.ico') }
      ],
      og: {
        site_name: 'Chiikoma',
        title: 'ちいこま',
        description: '「小さな困りごと」気にしてあげませんか？',
        type: 'website',
        url: 'https://chiikoma.herokuapp.com/',
        image: image_url('ogp.png'),
        locale: 'ja_JP'
      },
      twitter: {
        card: 'summary_large_image',
        site: '@takapi61'
      }
    }
  end
end

app/views/hassles/achievement/index.html.slim
- provide(:title, '１週間のがんばり')
.page
  .usage-container
    .title.is-centered
      | 1週間のがんばり
  .main-body
    .container.is-sm
      .date-container
        h1.date-list
          = l Time.current.beginning_of_week
          |   ~  
          = l Time.current.end_of_week

      .achievement-container
        .all-achievement-content
          .all-achievement-header 合計ちいこま
          .all-achievement-inners
            .all-achievement-inner
              .all-achievement-title ちいこま数
              .all-achievement-score = current_user.fetch_all_hassles_numbers
            .all-achievement-inner
              .all-achievement-title ポイント
              .all-achievement-score = current_user.fetch_all_hassles_points
        .each-achievement-container
          .registration-content
            .achievement-header.is-centered 登録したちいこま
            .chiikoma-inners
              .chiikoma-inner
                .achievement-subtitle ちいこま数
                .achievement-score = current_user.fetch_registration_numbers
              .chiikoma-inner
                .achievement-subtitle ポイント
                .achievement-score = current_user.fetch_registration_points
          .solved-content
            .achievement-header2.is-centered 解決したちいこま
            .chiikoma-inners
              .chiikoma-inner
                .achievement-subtitle ちいこま数
                .achievement-score = current_user.fetch_solution_numbers
              .chiikoma-inner
                .achievement-subtitle ポイント
                .achievement-score = current_user.fetch_solution_points
        .barhart
          = column_chart current_user.show_chart, stacked: true

app/views/hassles/done.html.slim
- provide(:title, 'ケア済みちいこま一覧')
.page
  .usage-container
    .title.is-centered
      | 解決した!
  .main-body
    .container.is-sm
      = javascript_pack_tag 'hassle-done'
      #js-hassle-done

app/views/hassles/edit.html.slim
- provide(:title, 'ちいこま情報編集')
.page
  .usage-container.is-centered
    .title
      | ちいこまの編集
  .main-body
    .container.is-sm
      = javascript_pack_tag 'hassle-edit'
      #js-hassle-edit

app/views/hassles/index.html.slim
- provide(:title, 'ちいこま一覧')
.page
  .usage-container
    .title.is-centered
      | ちいこま一覧
  .main-body
    .container.is-sm
      = javascript_pack_tag 'hassle-index'
      #js-hassle-index
      div id='hassle-index'

app/views/hassles/new.html.slim
- provide(:title, 'ちいこま登録')
.page
  .usage-container
    .title.is-centered
      | ちいこまの作成
  .main-body
    .container.is-sm
      = javascript_pack_tag 'hassle-new'
      #js-hassle-new

app/views/hassles/show.html.slim
- provide(:title, 'ちいこま詳細')
.page
  .usage-container
    .title.is-centered
      | ちいこま詳細
  .main-body
    .container.is-sm
      = javascript_pack_tag 'hassle-show'
      #js-hassle-show

app/views/layouts/_footer.html.slim
footer.footer.py-4
  .content.has-text-centered
    p.footer-items
      a.footer-item.mx-3 href="/tos"
        | 利用規約
      a.footer-item.mx-3 href="/privacy_policy"
        | プライバシーポリシー
      a.footer-item.mx-3 href="https://github.com/taka61/chiikoma"
        i class="fa-brands fa-github"
    footer-items
      .footer-item
        | ©️ 2022 takapi61

app/views/layouts/_header.html.slim
nav.navbar[role="navigation" aria-label="main navigation"]
  .navbar-brand
    a.navbar-logo[href="/hassles"]
      = image_tag 'logo.png', size: '112x28', alt: 'ヘッダーのロゴ'
  - if user_signed_in?
    a.navbar-burger[role="button" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample"]
      span[aria-hidden="true"]
      span[aria-hidden="true"]
      span[aria-hidden="true"]
    #navbarBasicExample.navbar-menu
      .navbar-start
        a.navbar-item[href="/hassles"]
          |  ちいこま一覧
        a.navbar-item[href="/hassles/achievement"]
          |  1週間のがんばり
        .navbar-item.has-dropdown.is-hoverable
          a.navbar-link
            |  アカウント
          .navbar-dropdown
            .navbar-item
              = link_to edit_user_registration_path, class: 'nav-items__item-link' do
                |  登録情報変更
            .navbar-item
              = link_to destroy_user_session_path, method: :delete, class: 'nav-items__item-link' do
                |  ログアウト

app/views/layouts/application.html.slim
doctype html
html
  title
    = full_title(yield(:title))
  head
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = display_meta_tags(default_meta_tags)
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_pack_tag 'application'
    = favicon_link_tag('favicon.ico')
    link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.0.0/css/all.css"
  body
    .wrapper
      .wrapper__start
        - if flash[:notice]
          .notification.is-centered.is-danger.is-light
            = flash[:notice]
        - if flash[:alert]
          .notification.is-centered.is-danger.is-light
            = flash[:alert]
        - if current_page?(root_path) && !user_signed_in?
          = yield
        - else
          = render 'layouts/header'
          = yield
      .wrapper__end
          = render 'layouts/footer'

app/views/welcome/index.html.slim
.top-page
  .main-body
    .top-container
      .top-title
        .main-image.is-centered
          = image_tag 'top.png', size: '350x250', alt: 'ちいこまのロゴ'
        h1.main-header.is-centered
          | 「あなたのためだけの問題」
          p
          | 管理しませんか？
        .button-section
          .main-button
            = link_to '始める', new_user_registration_path, class: 'button is-medium is-fullwidth button is-danger'
          .link-container.is-centered
            = link_to 'ログインはこちら', new_user_session_path, class: 'link-item'
      .main-items
        section.main-item
          h2.main-title.is-centered
            | いつか解決したいと思っている
            p
            | 自分のためだけの小さな困りごと「ちいこま」
          .main-description
            |「他人からの頼まれごと」や「やらなきゃいけない（Todo）コト」は手をつけやすく、
            p
            |「自分だけのため」・「小さな困りごと」はついつい後回しにしてしまう癖があります。
        section.main-item
          h2.main-title.is-centered
            | 小さなイライラ気づいていますか？
          .main-description
            |「小さく・緊急性がない」だけで、「解決できると（自分が）嬉しい」ものを放っておくのは、
            | 自分の内側からの欲求・SOSを無視しているのと同じことであり、
            | その状態を続けておくとストレスが少しずつ溜まっていきます。
        section.main-item
          h2.main-title.is-centered
            | セルフケアの第一歩に
          .main-description
            | ちいこまを使って自分の中の不快・違和感・欲求等を見える化し、
            | 自分のことをもっと気にかけてあげる第一歩を始めましょう！
      .sub-items
        section.service-article
          h1.service-header.is-centered
            | ちいこまにポイントをつけよう
          h2.service-description.is-centered
              |「 困り度」・「経験する頻度」・「対策コスト」の3つの観点で数値化
          .service-image.is-centered
            = image_tag 'chiikoma-new.png', size: '400x250', alt: '新規作成のデモ画面'
        section.service-article
          h1.service-header.is-centered
            | 1週間のがんばりをグラフで可視化
          h2.service-description.is-centered
              |「どれくらい自分の問題に気づくことができたか」・「問題を解決できたか」
              |1週間のがんばりが可視化できるからやる気が出るかも
          .service-image.is-centered
            = image_tag 'chiikoma-chart.png', size: '400x250', alt: '1週間のがんばりのデモ画面'
        section.service-article
          h1.service-header.is-centered
            | 日替わりでちいこまの提示
          h2.service-description.is-centered
              | 「自分だけの小さな困りごと」ってそもそも気づきにくい…
              | そんな方のために日替わりでちいこまを提示します。つい後回しにしていることに取り組むきっかけになるかも…？
          .service-image.is-centered
             = image_tag 'daily-chiikoma.png', size: '400x250', alt: '日替わり表示のデモ画面'
      .top-action
        .button-container
          .main-button
            = link_to '始める', new_user_registration_path, class: 'button is-medium is-fullwidth button is-danger'

app/views/welcome/privacy_policy.html.slim
.container
  .content
    h1.title.is-centered
      |プライバシーポリシー
    p
      | 本サービスは、ユーザーの個人情報の取扱いについて、以下のとおりプライバシーポリシー（以下、「本ポリシー」といいます。）を定めます。
    h3
      |  第1条（個人情報）
    p
      | 本サービスでは登録およびご利用に際して以下の情報を取得し、弊社はそれらを個人情報として取り扱います。
    ul
      li
        | メールアドレス
      li
        | Cookie(クッキー)を用いて生成された識別情報
      li
        | その他本サービスへのアクセス時に生成されるログ

    h3
      |  第2条（個人情報を収集・利用する目的）
    p
      | 本サービスは、お客様から取得した情報を、以下の目的のために利用します。
    ul
      li
        | 本サービスに関する登録の受付、お客様の本人確認、認証のため
      li
        | 本サービスに関するご案内をするため
      li
        | お客様からのお問い合わせに対応するため
      li
        | 本サービスの規約や法令に違反する行為に対応するため
      li
        | 本サービスの変更、提供中止、終了、契約解除をご連絡するため
      li
        | 本サービス規約の変更等を通知するため
      li
        | 以上の他、本サービスの提供、維持、保護及び改善のため

    h3
      | 第3条（個人情報の第三者提供）
    p
      | 本サービスでは、個人情報は適切に管理し、以下に該当する場合を除いて第三者に開示することはありません。
    ul
      li
        | 本人のご了解がある場合
      li
        | その他、法律によって合法的に第三者提供が許されている場合
    h3
      | 第4条（利用目的の変更）
    ol
      li
        | 本サービスは、利用目的が変更前と関連性を有すると合理的に認められる場合に限り、個人情報の利用目的を変更するものとします。
      li
        | 利用目的の変更を行った場合には、変更後の目的について、本サービス所定の方法により、ユーザーに通知し、または本ウェブサイト上に公表するものとします。
    h3
      | 第5条（プライバシーポリシーの変更）
    p
      | 本サービスは、必要に応じて、このプライバシーポリシーの内容を変更します。
      | この場合、変更後のプライバシーポリシーの施行時期と内容を適切な方法により周知または通知します。

    p
      | 以上。
    p
      | 2022年02月22日 制定

app/views/welcome/tos.html.slim
.container
  .content
    h1.title.is-centered
      |利用規約
    p
      | この利用規約（以下「本規約」といいます。）は、「ちいこま」（以下「本サービス」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下「ユーザー」といいます。）には、本規約に従って、本サービスをご利用いただきます。

    h3
      | 第1条（適用）
    ol
      li 本規約は、ユーザーの本サービスの利用に関わる一切の関係に適用されるものとします。
      li 本サービスに関し、本規約のほか、ご利用にあたってのルール等、各種の定め（以下「個別規定」といいます。）をすることがあります。これら個別規定はその名称のいかんに関わらず、本規約の一部を構成するものとします。
      li 本規約の規定が前条の個別規定の規定と矛盾する場合には、個別規定において特段の定めなき限り、個別規定の規定が優先されるものとします。

    h3
      | 第2条（利用登録）
    ol
      li 本サービスにおいては、登録希望者が本規約に同意の上、本サービスの定める方法によって利用登録を申請し、本サービスがこの承認を登録希望者に通知することによって、利用登録が完了するものとします。
      li 本サービスは、利用登録の申請者に以下の事由があると判断した場合、利用登録の申請を承認しないことがあり、その理由については一切の開示義務を負わないものとします。
      li
        ol
          li 利用登録の申請に際して虚偽の事項を届け出た場合
          li 本規約に違反したことがある者からの申請である場合
          li その他、本サービスが利用登録を相当でないと判断した場合

    h3
      | 第3条（ユーザーIDおよびパスワードの管理）
    ol
      li ユーザーは、自己の責任において、本サービスのユーザーIDおよびパスワードを適切に管理するものとします。
      li
        | ユーザーは、いかなる場合にも、ユーザーIDおよびパスワードを第三者に譲渡または貸与し、もしくは第三者と共用することはできません。
        | 本サービスは、ユーザーIDとパスワードの組み合わせが登録情報と一致してログインされた場合には、そのユーザーIDを登録しているユーザー自身による利用とみなします。
      li ユーザーID及びパスワードが第三者によって使用されたことによって生じた損害は、本サービスに故意又は重大な過失がある場合を除き、本サービスは一切の責任を負わないものとします。

    h3
      | 第4条（禁止事項）
    p
      | ユーザーは、本サービスの利用にあたり、以下の行為をしてはなりません。
    ol
      li 法令または公序良俗に違反する行為
      li 犯罪行為に関連する行為
      li 本サービスの他のユーザー，または第三者のサーバーまたはネットワークの機能を破壊したり，妨害したりする行為
      li 本サービスのサービスの運営を妨害するおそれのある行為
      li 不正アクセスをし、またはこれを試みる行為
      li 他のユーザーに関する個人情報等を収集または蓄積する行為
      li 不正な目的を持って本サービスを利用する行為
      li 本サービスの他のユーザーまたはその他の第三者に不利益、損害、不快感を与える行為
      li 他のユーザーに成りすます行為
      li 本サービスが許諾しない本サービス上での宣伝、広告、勧誘、または営業行為
      li 本サービスのサービスに関連して、反社会的勢力に対して直接または間接に利益を供与する行為
      li その他、本サービスが不適切と判断する行為

    h3
      | 第5条（本サービスの提供の停止等）
    ol
      li 以下のいずれかの事由があると判断した場合、ユーザーに事前に通知することなく本サービスの全部または一部の提供を停止または中断することができるものとします。
      li
        ol
          li 本サービスにかかるコンピュータシステムの保守点検または更新を行う場合
          li 地震、落雷、火災、停電または天災などの不可抗力により、本サービスの提供が困難となった場合
          li コンピュータまたは通信回線等が事故により停止した場合
          li その他、本サービスの提供が困難と判断した場合

    h3
      | 第6条（利用制限および登録抹消）
    ol
      li 本サービスは、ユーザーが以下のいずれかに該当する場合には、事前の通知なく、投稿データを削除し、ユーザーに対して本サービスの全部もしくは一部の利用を制限しまたはユーザーとしての登録を抹消することができるものとします。
        ol
          li 本規約のいずれかの条項に違反した場合
          li 登録事項に虚偽の事実があることが判明した場合
          li 料金等の支払債務の不履行があった場合
          li 本サービスからの連絡に対し、一定期間返答がない場合
          li 本サービスについて、最終の利用から一定期間利用がない場合
          li その他、本サービスが本サービスの利用を適当でないと判断した場合
      li 本条に基づき本サービスが行った行為によりユーザーに生じた損害について、一切の責任を負いません。

    h3
      | 第7条（退会）
    p
      | ユーザーは、本サービスの定める退会手続により、本サービスから退会できるものとします。

    h3
      | 第8条（保証の否認および免責事項）
    ol
      li 本サービスに事実上または法律上の瑕疵（安全性、信頼性、正確性、完全性、有効性、特定の目的への適合性、セキュリティなどに関する欠陥、エラーやバグ、権利侵害などを含みます。）がないことを明示的にも黙示的にも保証しておりません。
      li 本サービスに起因してユーザーに生じたあらゆる損害について一切の責任を負いません。ただし、本サービスに関するユーザーとの間の契約（本規約を含みます。）が消費者契約法に定める消費者契約となる場合、この免責規定は適用されません。
      li
        | 前項ただし書に定める場合であっても、本サービスは、本サービスの過失（重過失を除きます。）による債務不履行または不法行為により
        | ユーザーに生じた損害のうち特別な事情から生じた損害（本サービスまたはユーザーが損害発生につき予見し、または予見し得た場合を含みます。）について一切の責任を負いません。
      li 本サービスに関して、ユーザーと他のユーザーまたは第三者との間において生じた取引、連絡または紛争等について一切責任を負いません。

    h3
      | 第9条（サービス内容の変更等）
    p
      | 本サービスは、ユーザーに通知することなく、本サービスの内容を変更しまたは本サービスの提供を中止することができるものとし、これによってユーザーに生じた損害について一切の責任を負いません。

    h3
      | 第10条（利用規約の変更）
    p
      | 本サービスは、必要と判断した場合には、ユーザーに通知することなくいつでも本規約を変更することができるものとします。なお、本規約の変更後、本サービスの利用を開始した場合には、当該ユーザーは変更後の規約に同意したものとみなします。

    h3
      | 第11条（個人情報の取扱い）
    p
      | 本サービスは、本サービスの利用によって取得する個人情報については、本サービス「
      = link_to 'プライバシーポリシー', privacy_policy_path
      | 」に従い適切に取り扱うものとします。

    h3
      | 第12条（通知または連絡）
    p
      | ユーザーと本サービスとの間の通知または連絡は、本サービスの定める方法によって行うものとします。
      | 本サービスはユーザーから本サービスが別途定める方式に従った変更届け出がない限り、現在登録されている連絡先が有効なものとみなして当該連絡先へ通知または連絡を行い、これらは、発信時にユーザーへ到達したものとみなします。

    h3
      | 第13条（権利義務の譲渡の禁止）
    p
      | ユーザーは、本サービスの書面による事前の承諾なく、利用契約上の地位または本規約に基づく権利もしくは義務を第三者に譲渡し、または担保に供することはできません。

    h3
      | 第14条（準拠法・裁判管轄）
    ol
      li 本規約の解釈にあたっては、日本法を準拠法とします。
      li 本サービスに関して紛争が生じた場合には、本サービスの本店所在地を管轄する裁判所を専属的合意管轄とします。

    p
      | 以上。
    p
      | 2022年2月22日制定